[package]
name = "dasrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.22"
glob = "0.3.1"
chrono = "0.4"
